version: "3.5"
services:
  envoy:
    build:
      context: ../
      dockerfile: ./deployments/docker/envoy/Dockerfile
    image: grpc-exam-envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    links:
      - api
  api:
    build:
      context: ../
      dockerfile: ./deployments/docker/api/Dockerfile
    image: grpc-exam-api
    ports:
      - "9090:9090"
  web:
    build:
      context: ../
      dockerfile: ./deployments/docker/web/Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:8080
    image: grpc-exam-web
    ports:
      - "3001:80"
